
GET http://127.0.0.1:8000/owners/

###
POST http://127.0.0.1:8000/owners/ 
Content-Type: application/json

{
    "first_name": "Theodor Albeit",
    "last_name": "Hrushevich"
}

###
GET http://127.0.0.1:8000/cats/

###
GET http://127.0.0.1:8000/cats/7

###
POST http://127.0.0.1:8000/cats/
Content-Type: application/json

{
    "name": "Снежок11",
    "color": "White",
    "birth_year": "2020",
    "owner": "2",
    "achievements": [
        {"achievement_name": "Поймал мышь"},
        {"achievement_name": "Разбил вазу"}
    ]
}

###
POST http://127.0.0.1:8000/cats/
Content-Type: application/json

{
    "name": "Левий Потапыч",
    "color": "Стеганый",
    "birth_year": "2018",
    "owner": "1"
}
